spring:
  jpa:
    properties:
# uncomment to create database schema
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        orm:
          jdbc:
#            bind: trace # uncomment for bind value debugging
