spring:
  jpa:
    properties:
# uncomment to create database schema
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata
      hibernate:
        show_sql: true
        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
