server:
  port: 5000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        validator:
          apply_to_ddl: true
#        current_session_context_class: thread, check what is it
    hibernate:
      ddl-auto: create
    show-sql: true
#    open-in-view: # false, commented temporary
    database: postgresql

springdoc:
  swagger-ui:
    docExpansion: none
    tagsSorter: alpha
    operations-sorter: alpha
    path: /docs
