server:
  port: 5000
  servlet:
    context-path: /api

spring:
  security:
    user:
      name: admin
      password: admin.123
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        validator:
          apply_to_ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    database: postgresql

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: alpha
    path: /docs
