version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/dev/postgres:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
    ports:
      - "5432:5432"
    networks:
      - play-together
    restart: unless-stopped
  proxy:
    build: ../dev-proxy
    ports:
      - "80:80"
    networks:
        - play-together

networks:
  play-together:
    driver: bridge
