version: '3.1'

services:
#  api:
#    image: "6745345/play-together-api:1.0"
#    container_name: "api"
#    expose:
#      - "5000"
#    ports:
#      - "5000:5000"
#    networks:
#      - play-together
#    depends_on:
#        - postgres
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/dev/postgres:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - play-together
  proxy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ../dev-proxy
    ports:
      - "80:80"

networks:
  play-together:
    driver: bridge
